# Generated by Django 5.1.7 on 2025-03-18 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Изображение для поста.",
                null=True,
                upload_to="posts/",
                verbose_name="Изображение",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(
                help_text="Основной текст поста.", verbose_name="Контент поста"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Дата, когда пост был создан.",
                verbose_name="Дата создания",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="rubric",
            field=models.ForeignKey(
                help_text="Рубрика, к которой относится данный пост.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="blog.rubric",
                verbose_name="Рубрика",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(
                help_text="Заголовок поста.",
                max_length=255,
                verbose_name="Заголовок поста",
            ),
        ),
        migrations.AlterField(
            model_name="rubric",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Описание рубрики для SEO.",
                verbose_name="Описание рубрики",
            ),
        ),
        migrations.AlterField(
            model_name="rubric",
            name="name",
            field=models.CharField(
                help_text="Название рубрики, которое будет отображаться на сайте.",
                max_length=255,
                verbose_name="Название рубрики",
            ),
        ),
        migrations.CreateModel(
            name="SeoMeta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Мета-заголовок для SEO.",
                        max_length=255,
                        verbose_name="Мета-Title",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Мета-описание для SEO.", verbose_name="Мета-Описание"
                    ),
                ),
                (
                    "keywords",
                    models.CharField(
                        blank=True,
                        help_text="Ключевые слова для SEO.",
                        max_length=255,
                        verbose_name="Мета-Ключевые слова",
                    ),
                ),
                (
                    "robots",
                    models.CharField(
                        blank=True,
                        help_text="Настройки для поисковых роботов (например, 'index, follow').",
                        max_length=255,
                        verbose_name="Мета-Роботы",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "SEO Мета-теги",
                "verbose_name_plural": "SEO Мета-теги",
            },
        ),
    ]
