# Generated by Django 5.1.7 on 2025-03-18 17:02

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_post_image_alter_post_content_alter_post_created_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={
                "ordering": ["-updated_at"],
                "verbose_name": "Пост",
                "verbose_name_plural": "Посты",
            },
        ),
        migrations.AlterModelOptions(
            name="rubric",
            options={
                "ordering": ["-updated_at"],
                "verbose_name": "Рубрика",
                "verbose_name_plural": "Рубрики",
            },
        ),
        migrations.AlterModelOptions(
            name="seometa",
            options={
                "ordering": ["-updated_at"],
                "verbose_name": "SEO Мета-теги",
                "verbose_name_plural": "SEO Мета-теги",
            },
        ),
        migrations.AddField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Черновик"),
                    ("published", "Опубликован"),
                    ("archived", "Архивирован"),
                ],
                default="draft",
                help_text="Статус поста: Черновик, Опубликован или Архивирован.",
                max_length=10,
                verbose_name="Статус публикации",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Дата последнего изменения поста.",
                verbose_name="Дата последнего обновления",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="post_updates",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Последний обновивший",
            ),
        ),
        migrations.AddField(
            model_name="rubric",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2025, 3, 18, 17, 2, 43, 947571, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Дата создания",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rubric",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Дата последнего обновления"
            ),
        ),
        migrations.AddField(
            model_name="rubric",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rubric_updates",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Последний обновивший",
            ),
        ),
        migrations.AddField(
            model_name="seometa",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Дата создания",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="seometa",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Дата последнего обновления"
            ),
        ),
        migrations.AddField(
            model_name="seometa",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="seo_meta_updates",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Последний обновивший",
            ),
        ),
        migrations.AlterField(
            model_name="seometa",
            name="robots",
            field=models.CharField(
                choices=[
                    ("index, follow", "Индексировать, следовать"),
                    ("noindex, nofollow", "Не индексировать, не следовать"),
                    ("noindex, follow", "Не индексировать, следовать"),
                    ("index, nofollow", "Индексировать, не следовать"),
                ],
                default="index, follow",
                help_text="Настройки для поисковых роботов (например, 'index, follow').",
                max_length=255,
                verbose_name="Мета-Роботы",
            ),
        ),
    ]
