# Generated by Django 5.1.7 on 2025-03-18 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_post_options_alter_rubric_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="seometa",
            name="keywords",
        ),
    ]
